// dart format width=80
// Generated by mysql_native_connector_generator — do not edit.

part of 'cliente_model.dart';

// **************************************************************************
// MysqlEloquentGenerator
// **************************************************************************

// ignore_for_file: type=lint, unused_element

/// Motor Eloquent gerado para [ClienteModel].
class _ClienteModelMysql {
  _ClienteModelMysql._();

  static const table = 'clientes';
  static const primaryKey = 'cli_codigo';
  static const columns = [
    'cli_codigo',
    'cli_nome',
    'cli_fantasia',
    'cli_cgc',
    'cli_endereco',
  ];

  static final schema = MysqlTableSchema(
    name: table,
    primaryKey: primaryKey,
    columns: columns,
    joins: [
      MysqlJoinSpec(
        table: 'cliente_enderecos',
        localKey: 'cli_codigo',
        foreignKey: 'end_cli',
        alias: 'enderecoCli',
        columns: [
          'end_id',
          'end_cli',
          'end_endereco',
          'end_cidade',
          'end_uf',
          'end_bairro',
        ],
      ),
    ],
  );

  static final repo = MysqlRepository<ClienteModel>(
    schema: schema,
    fromRow: fromRow,
    toColumns: toColumns,
    idOf: (m) => m.codigo,
  );

  static final box = Mysql.register<ClienteModel>(
    repo,
    defaultOrderBy: '`cli_nome` ASC',
  );

  static ClienteModel fromRow(MysqlRow row) {
    return ClienteModel(
      codigo: row.string('cli_codigo'),
      nome: row.string('cli_nome'),
      fantasia: row.asString('cli_fantasia'),
      cgc: row.asString('cli_cgc'),
      endereco: row.asString('cli_endereco'),
      enderecoCli: (row['enderecoCli__end_id'] == null)
          ? null
          : EnderecoCliModel(
              id: (row.asInt('enderecoCli__end_id') ?? 0),
              codigoCliente: row.string('enderecoCli__end_cli'),
              endereco: row.string('enderecoCli__end_endereco'),
              cidade: row.string('enderecoCli__end_cidade'),
              uf: row.string('enderecoCli__end_uf'),
              bairro: row.string('enderecoCli__end_bairro'),
            ),
    );
  }

  static Map<String, Object?> toColumns(ClienteModel m) => {
    'cli_codigo': m.codigo,
    'cli_nome': m.nome,
    'cli_fantasia': m.fantasia,
    'cli_cgc': m.cgc,
    'cli_endereco': m.endereco,
  };
}

extension ClienteModelMysqlColumns on ClienteModel {
  Map<String, Object?> toColumns() => _ClienteModelMysql.toColumns(this);
}
