// Generated by mysql_native_connector_generator — do not edit.
// ignore_for_file: type=lint, unused_element

part of 'cliente_model.dart';

/// Motor Eloquent gerado para [ClienteModel].
class _ClienteModelMysql {
  _ClienteModelMysql._();

  static const table = 'clientes';
  static const primaryKey = 'cli_codigo';
  static const columns = [
    'cli_codigo',
    'cli_nome',
    'cli_fantasia',
    'cli_cgc',
    'cli_endereco',
  ];

  static final schema = MysqlTableSchema(
    name: table,
    primaryKey: primaryKey,
    columns: columns,
  );

  static final repo = MysqlRepository<ClienteModel>(
    schema: schema,
    fromRow: fromRow,
    toColumns: toColumns,
    idOf: (m) => m.codigo,
  );

  static MysqlQuery<ClienteModel> query() => repo.query();

  static Future<List<ClienteModel>> index({int limit = 50}) {
    return repo.all(limit: limit, orderBy: '`cli_nome` ASC');
  }

  static Future<ClienteModel?> show(Object id) => repo.find(id);

  static Future<ClienteModel> store(ClienteModel model) => repo.save(model);

  static Future<ClienteModel> update(ClienteModel model) async {
    final existing = await show(model.codigo);
    if (existing == null) {
      throw StateError('ClienteModel ${model.codigo} não encontrado.');
    }
    return repo.save(model);
  }

  static Future<bool> destroy(Object id) => repo.deleteById(id);

  static Future<List<ClienteModel>> raw(String sql) => repo.raw(sql);

  static ClienteModel fromRow(MysqlRow row) {
    return ClienteModel(
      codigo: row.string('cli_codigo'),
      nome: row.string('cli_nome'),
      fantasia: row.asString('cli_fantasia'),
      cgc: row.asString('cli_cgc'),
      endereco: row.asString('cli_endereco'),
    );
  }

  static Map<String, Object?> toColumns(ClienteModel m) => {
        'cli_codigo': m.codigo,
        'cli_nome': m.nome,
        'cli_fantasia': m.fantasia,
        'cli_cgc': m.cgc,
        'cli_endereco': m.endereco,
      };
}

extension ClienteModelMysqlInstance on ClienteModel {
  Future<ClienteModel> save() => _ClienteModelMysql.store(this);
  Future<bool> delete() => _ClienteModelMysql.destroy(codigo);
  Map<String, Object?> toColumns() => _ClienteModelMysql.toColumns(this);
}
