// dart format width=80
// Generated by mysql_native_connector_generator — do not edit.

part of 'endere_cli_model.dart';

// **************************************************************************
// MysqlEloquentGenerator
// **************************************************************************

// ignore_for_file: type=lint, unused_element

/// Motor Eloquent gerado para [EnderecoCliModel].
class _EnderecoCliModelMysql {
  _EnderecoCliModelMysql._();

  static const table = 'cliente_enderecos';
  static const primaryKey = 'end_id';
  static const columns = [
    'end_id',
    'end_cli',
    'end_endereco',
    'end_cidade',
    'end_uf',
    'end_bairro',
  ];

  static final schema = MysqlTableSchema(
    name: table,
    primaryKey: primaryKey,
    columns: columns,
    joins: const [],
  );

  static final repo = MysqlRepository<EnderecoCliModel>(
    schema: schema,
    fromRow: fromRow,
    toColumns: toColumns,
    idOf: (m) => m.id,
  );

  static final box = Mysql.register<EnderecoCliModel>(
    repo,
    defaultOrderBy: '`id` ASC',
  );

  static EnderecoCliModel fromRow(MysqlRow row) {
    return EnderecoCliModel(
      id: (row.asInt('end_id') ?? 0),
      codigoCliente: row.string('end_cli'),
      endereco: row.string('end_endereco'),
      cidade: row.string('end_cidade'),
      uf: row.string('end_uf'),
      bairro: row.string('end_bairro'),
    );
  }

  static Map<String, Object?> toColumns(EnderecoCliModel m) => {
    'end_id': m.id,
    'end_cli': m.codigoCliente,
    'end_endereco': m.endereco,
    'end_cidade': m.cidade,
    'end_uf': m.uf,
    'end_bairro': m.bairro,
  };
}

extension EnderecoCliModelMysqlColumns on EnderecoCliModel {
  Map<String, Object?> toColumns() => _EnderecoCliModelMysql.toColumns(this);
}
