// Generated by mysql_native_connector_generator — do not edit.
// ignore_for_file: type=lint, unused_element

part of 'endereco_model.dart';

/// Motor Eloquent gerado para [EnderecoModel].
class _EnderecoModelMysql {
  _EnderecoModelMysql._();

  static const table = 'enderecos';
  static const primaryKey = 'end_codigo';
  static const columns = [
    'end_codigo',
    'end_cliente',
    'end_logradouro',
    'end_cidade',
  ];

  static final schema = MysqlTableSchema(
    name: table,
    primaryKey: primaryKey,
    columns: columns,
    joins: const [],
  );

  static final repo = MysqlRepository<EnderecoModel>(
    schema: schema,
    fromRow: fromRow,
    toColumns: toColumns,
    idOf: (m) => m.id,
  );

  static final box = Mysql.register<EnderecoModel>(
    repo,
    defaultOrderBy: null,
  );

  static EnderecoModel fromRow(MysqlRow row) {
    return EnderecoModel(
      id: row.string('end_codigo'),
      clienteCodigo: row.asString('end_cliente'),
      logradouro: row.asString('end_logradouro'),
      cidade: row.asString('end_cidade'),
    );
  }

  static Map<String, Object?> toColumns(EnderecoModel m) => {
        'end_codigo': m.id,
        'end_cliente': m.clienteCodigo,
        'end_logradouro': m.logradouro,
        'end_cidade': m.cidade,
      };
}

extension EnderecoModelMysqlColumns on EnderecoModel {
  Map<String, Object?> toColumns() => _EnderecoModelMysql.toColumns(this);
}
