import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'src/mysql_eloquent_generator.dart';

Builder mysqlEloquentBuilder(BuilderOptions options) => PartBuilder(
      [MysqlEloquentGenerator()],
      '.mysql.g.dart',
      header: '// Generated by mysql_native_connector_generator — do not edit.',
    );
