// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_cell`, `fallback_text_or_null`, `pool_snapshot`, `type_is`

/// Abre (ou substitui) o pool MySQL. Credenciais vêm do Dart (`geral.ini`).
Future<void> initDbPool({required String url, required int maxConnections}) =>
    RustLib.instance.api.crateApiDatabaseInitDbPool(
      url: url,
      maxConnections: maxConnections,
    );

/// SELECT → colunas + linhas tipadas.
Future<NativeQueryResult> querySql({required String sql}) =>
    RustLib.instance.api.crateApiDatabaseQuerySql(sql: sql);

/// INSERT / UPDATE / DELETE → linhas afetadas.
Future<BigInt> executeSql({required String sql}) =>
    RustLib.instance.api.crateApiDatabaseExecuteSql(sql: sql);

/// Fecha o pool explicitamente (ciclo de vida da sessão).
Future<void> closeDbPool() =>
    RustLib.instance.api.crateApiDatabaseCloseDbPool();

Future<bool> isDbPoolOpen() =>
    RustLib.instance.api.crateApiDatabaseIsDbPoolOpen();
