// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`

@freezed
sealed class DbError with _$DbError implements FrbException {
  const DbError._();

  const factory DbError.emptyUrl() = DbError_EmptyUrl;
  const factory DbError.emptySql() = DbError_EmptySql;
  const factory DbError.poolNotInitialized() = DbError_PoolNotInitialized;
  const factory DbError.connect(String field0) = DbError_Connect;
  const factory DbError.query(String field0) = DbError_Query;
  const factory DbError.execute(String field0) = DbError_Execute;
  const factory DbError.column({
    required BigInt index,
    required String message,
  }) = DbError_Column;
}
