// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
sealed class CellValue with _$CellValue {
  const CellValue._();

  const factory CellValue.null_() = CellValue_Null;
  const factory CellValue.bool(bool field0) = CellValue_Bool;
  const factory CellValue.int64(PlatformInt64 field0) = CellValue_Int64;
  const factory CellValue.float64(double field0) = CellValue_Float64;
  const factory CellValue.text(String field0) = CellValue_Text;
  const factory CellValue.bytes(Uint8List field0) = CellValue_Bytes;
}

/// Resultado tabular devolvido ao Dart via flutter_rust_bridge.
class NativeQueryResult {
  final List<String> columns;
  final List<List<CellValue>> rows;
  final BigInt? rowsAffected;
  final BigInt durationMs;

  const NativeQueryResult({
    required this.columns,
    required this.rows,
    this.rowsAffected,
    required this.durationMs,
  });

  @override
  int get hashCode =>
      columns.hashCode ^
      rows.hashCode ^
      rowsAffected.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeQueryResult &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          rows == other.rows &&
          rowsAffected == other.rowsAffected &&
          durationMs == other.durationMs;
}
